apiVersion: apps/v1
kind: Deployment
metadata:
  name: zelox-spark-server
spec:
  template:
    spec:
      volumes:
        - name: data
          hostPath:
            path: /tmp/sail
            type: DirectoryOrCreate
        - name: pytest-data
          hostPath:
            path: /private/tmp/sail
            type: DirectoryOrCreate
      containers:
        - name: server
          volumeMounts:
            - name: data
              mountPath: /tmp/sail
            - name: pytest-data
              mountPath: /private/tmp/sail
          env:
            - name: ZELOX_KUBERNETES__WORKER_POD_TEMPLATE
              value: |
                {
                  "metadata": {
                    "labels": {
                      "custom-label": "zelox-worker",
                      "environment": "development",
                      "component": "spark-worker"
                    }
                  },
                  "spec": {
                    "volumes": [
                      {
                        "name": "data",
                        "hostPath": {
                          "path": "/tmp/sail",
                          "type": "DirectoryOrCreate"
                        }
                      },
                      {
                        "name": "pytest-data",
                        "hostPath": {
                          "path": "/private/tmp/sail",
                          "type": "DirectoryOrCreate"
                        }
                      }
                    ],
                    "containers": [
                      {
                        "name": "worker",
                        "volumeMounts": [
                          {
                            "name": "data",
                            "mountPath": "/tmp/sail"
                          },
                          {
                            "name": "pytest-data",
                            "mountPath": "/private/tmp/sail"
                          }
                        ]
                      }
                    ]
                  }
                }
