apiVersion: v1
kind: Namespace
metadata:
  name: zelox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zelox-spark-server
  namespace: zelox
  labels:
    app.kubernetes.io/name: zelox
    app.kubernetes.io/component: spark-server
spec:
  # We cannot have more than one replica because each Spark session is tied to a single pod.
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zelox
      app.kubernetes.io/component: spark-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zelox
        app.kubernetes.io/component: spark-server
    spec:
      serviceAccountName: zelox-user
      volumes:
        - name: tmp-zelox
          hostPath:
            path: /private/tmp/zelox
            type: DirectoryOrCreate
        - name: tmp-zelox-alt
          hostPath:
            path: /tmp/zelox
            type: DirectoryOrCreate
      containers:
        - name: server
          image: zelox:latest
          command: [ "zelox" ]
          args: [ "server", "--ip", "0.0.0.0", "--port", "50051" ]
          ports:
            - containerPort: 50051
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tmp-zelox
              mountPath: /private/tmp/zelox
            - name: tmp-zelox-alt
              mountPath: /tmp/zelox
          env:
            - name: RUST_LOG
              value: info
            - name: ZELOX_MODE
              value: "kubernetes-cluster"
            - name: ZELOX_CLUSTER__DRIVER_LISTEN_HOST
              value: "0.0.0.0"
            - name: ZELOX_CLUSTER__DRIVER_EXTERNAL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ZELOX_KUBERNETES__IMAGE
              value: zelox:latest
            - name: ZELOX_KUBERNETES__NAMESPACE
              value: zelox
            - name: ZELOX_KUBERNETES__DRIVER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZELOX_KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME
              value: zelox-user
            - name: ZELOX_KUBERNETES__WORKER_POD_TEMPLATE
              value: >-
                {"spec":{"volumes":[{"name":"tmp-zelox","hostPath":{"path":"/private/tmp/zelox","type":"DirectoryOrCreate"}},{"name":"tmp-zelox-alt","hostPath":{"path":"/tmp/zelox","type":"DirectoryOrCreate"}}],"containers":[{"name":"worker","volumeMounts":[{"name":"tmp-zelox","mountPath":"/private/tmp/zelox"},{"name":"tmp-zelox-alt","mountPath":"/tmp/zelox"}]}]}}
---
apiVersion: v1
kind: Service
metadata:
  name: zelox-spark-server
  namespace: zelox
  labels:
    app.kubernetes.io/name: zelox
    app.kubernetes.io/component: spark-server
spec:
  selector:
    app.kubernetes.io/name: zelox
    app.kubernetes.io/component: spark-server
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zelox-spark-server
  namespace: zelox
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "*" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zelox-user
  namespace: zelox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zelox-spark-server
  namespace: zelox
subjects:
  - kind: ServiceAccount
    name: zelox-user
    namespace: zelox
roleRef:
  kind: Role
  name: zelox-spark-server
  apiGroup: rbac.authorization.k8s.io
