{{- if and .Values.podDisruptionBudget.enabled (eq .Values.mode "kubernetes-cluster") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "vajra.fullname" . }}-workers
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vajra.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "vajra.workerSelectorLabels" . | nindent 6 }}
{{- end }}
